import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";

import AuthContextProvider from "@/context_providers/AuthContext";
import WebSocketProvider from "@/context_providers/WebSocketContext";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <AuthContextProvider>
        <WebSocketProvider>
          <body className="flex flex-col md:flex-row h-full min-h-screen font-sans">
            {children}
          </body>
        </WebSocketProvider>
      </AuthContextProvider>
    </html>
  );
}
